version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    platform: linux/amd64
    container_name: metrics-mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "SuaSenhaForte!2025"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data:
